# Generated by Django 5.0.7 on 2024-07-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='no_brand', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, default='no_model', max_length=25),
        ),
    ]
